server:
  port: 8084

spring:
  application:
    name: eureka-consumer-feign

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka

feign:
  hystrix:
    enabled: true


hystrix:
  command:
    default:
      circuitBreaker:
        enabled: true
        requestVolumeThreshold: 5
        sleepWindowInMilliseconds: 5000