server:
  port: 8085

spring:
  application:
    name: eureka-gateway
  cloud:
    gateway:
      routes:
        - id: ribbon-consumer
          uri: lb://CONSUMER-RIBBON
          predicates:
            - Path=/eurekaConsumer/**
          filters:
            - StripPrefix=1

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka